--Vulcanite, Cryonite, vitamelange, beryllium, holmium, iridium, water ice, methane ice, naquium ore, imersite, liquid matter, rocket fuel
if mods["Krastorio2"] then
    repltech_recipe('rifle-magazine', 'device2')
    repltech_recipe('armor-piercing-rifle-magazine', 'device3')
    repltech_recipe('anti-material-rifle-magazine', 'device4')
    repltech_recipe('imersite-rifle-magazine', 'device5')
    repltech_recipe('uranium-anti-material-rifle-magazine', 'device5')
    repltech_recipe('imersite-anti-material-rifle-magazine', 'device5')
    repltech_recipe('piercing-shotgun-shell', 'device3')
    repltech_recipe('impulse-rifle-ammo', 'device5')
    repltech_recipe('kr-rocket-turret', 'device5')
    repltech_recipe('explosive-turret-rocket', 'device5')
    repltech_recipe('kr-railgun-turret', 'device5')
    repltech_recipe('basic-railgun-shell', 'device5')
    repltech_recipe('steel-wall', 'device5')
    repltech_recipe('raw-rare-metals', 'ore')
    repltech_recipe('rare-metals', 'device2')
    repltech_recipe('sand', 'ore')
    repltech_recipe('kr-advanced-transport-belt', 'device5')
    repltech_recipe('kr-superior-transport-belt', 'device5')
    repltech_recipe('kr-superior-inserter', 'device5')
    repltech_recipe('kr-superior-long-inserter', 'device5')
    repltech_recipe('kr-superior-long-filter-inserter', 'device5')
    repltech_recipe('first-aid-kit', 'device3')
    repltech_recipe('coke', 'device2')
    repltech_recipe('fertilizer', 'device2')
    repltech_recipe('biomass', 'alien')
    repltech_recipe('inserter', 'device3')
    repltech_recipe('raw-imersite', 'device5')
end